### ISSUE TITLE
failed to parse XML 

### ISSUE THREAD

**Issue by ymote** [Leonidas-from-XIV/node-xml2js#192]
Hi,

What is the options to parse the following XML? I used default setting but it stops at testcase and would not parse the rest. Thanks.

<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
<testsuite name="Frisby Test: Test Runner API" errors="0" tests="1" failures="1" time="9.021" timestamp="2015-04-20T00:46:22">
  <testcase classname="Frisby Test: Test Runner API" name="
        [ GET http://api-server.4a9b955a7a64.ip-10-10-1-109.sfo3.abcde.com ]" time="9.016"><failure type="expect" message="Expected 500 to equal 200.">Error: Expected 500 to equal 200.
    at new jasmine.ExpectationResult (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toEqual (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1316:29)
    at null.&amp;lt;anonymous&amp;gt; (/Users/y90988/Yue/salt/node_modules/frisby/lib/frisby.js:493:42)
    at null.&amp;lt;anonymous&amp;gt; (/Users/y90988/Yue/salt/node_modules/frisby/lib/frisby.js:1074:43)
    at jasmine.Block.execute (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1145:17)
    at jasmine.Queue.next_ (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2177:31)
    at null._onTimeout (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2167:18)
    at Timer.listOnTimeout (timers.js:110:15)</failure><failure type="expect" message="Expected &amp;apos;Destination URL may be down or URL is invalid, Error: ETIMEDOUT&amp;apos; to contain &amp;apos;Live4Code Runner&amp;apos;.">Error: Expected &amp;apos;Destination URL may be down or URL is invalid, Error: ETIMEDOUT&amp;apos; to contain &amp;apos;Live4Code Runner&amp;apos;.
    at new jasmine.ExpectationResult (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toContain (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1316:29)
    at null.&amp;lt;anonymous&amp;gt; (/Users/y90988/Yue/salt/node_modules/frisby/lib/frisby.js:545:42)
    at null.&amp;lt;anonymous&amp;gt; (/Users/y90988/Yue/salt/node_modules/frisby/lib/frisby.js:1074:43)
    at jasmine.Block.execute (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1145:17)
    at jasmine.Queue.next_ (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2177:31)
    at null._onTimeout (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2167:18)
    at Timer.listOnTimeout (timers.js:110:15)</failure></testcase>
</testsuite>
</testsuites>

**Comment by Leonidas-from-XIV** [comment]
Can you provide a complete code snippet to reproduce?

**Comment by jcsahnwaldt** [comment]
I think this can be closed.
