### ISSUE TITLE
"TypeError: Cannot read property '$ns' of undefined"

### ISSUE THREAD

**Issue by hhm0** [Leonidas-from-XIV/node-xml2js#208]
When parsing a file like so...

```
<?xml version="1.0" encoding="UTF-8"?>
<catalog version="1.0">
  <files>
    <file uri="file:///home/[whatever]"/>
    ...
  </files>
</catalog>
```

...with <a href="https://github.com/peerlibrary/node-xml4js">node-xml4js</a>, the following traceback is encountered:

```
TypeError: Cannot read property '$ns' of undefined
    at Object.onopentag (/home/[whatever]/node_modules/xml4js/node_modules/xml2js/lib/xml2js.js:277:29)
    at emit (/home/[whatever]/node_modules/xml4js/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/[whatever]/node_modules/xml4js/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at openTag (/home/[whatever]/node_modules/xml4js/node_modules/xml2js/node_modules/sax/lib/sax.js:801:3)
    at Object.write (/home/[whatever]/node_modules/xml4js/node_modules/xml2js/node_modules/sax/lib/sax.js:1261:31)
    at Parser.exports.Parser.Parser.parseString (/home/[whatever]/node_modules/xml4js/node_modules/xml2js/lib/xml2js.js:411:31)
    at /home/[whatever]/node_modules/xml4js/lib/parser.js:117:41
    at Object.async.until (/home/[whatever]/node_modules/xml4js/node_modules/async/lib/async.js:712:13)
    at /home/[whatever]/node_modules/xml4js/lib/parser.js:64:13
    at /home/[whatever]/node_modules/xml4js/lib/xsd.js:641:7
```

**Comment by tamitutor** [comment]
+1

**Comment by QAnders** [comment]
I got a similar one:

Cannot read property 'soapenv:Envelope' of undefined at /var/task/qip-lambda-company-search.js:33:25 at Parser.<anonymous> (/var/task/node_modules/xml2js/lib/xml2js.js:487:18) at emitOne (events.js:77:13) at Parser.emit (events.js:169:7) at Object.onerror (/var/task/node_modules/xml2js/lib/xml2js.js:308:26
2016-12-12T16:49:23.252Z	ee114e2c-c08a-11e6-b8cb-a398f73738f7	TypeError: Cannot read property 'soapenv:Envelope' of undefined

**Comment by Leonidas-from-XIV** [comment]
Uhm, this is not xml4js? (Though xml4js looks like a neat library)

**Comment by QAnders** [comment]
Uh, oh... Didn't notice that but my issue was with xml2js but I just now found that it is an encoding issue for Swedish characters... Forcing the XML string to UTF-8 solves my issue!
Thanks for an awesome package!

**Comment by jcsahnwaldt** [comment]
@hhm0 Can this issue be closed?
