### ISSUE TITLE
 Text data outside of root node.

### ISSUE THREAD

**Issue by CooCooooo** [Leonidas-from-XIV/node-xml2js#217]
Error: Text data outside of root node.
Line: 1
Column: 310
Char: T
    at error (C:\Users\zhou\Desktop\CooCoo\note\node_modules\xml2js\node_modules
\sax\lib\sax.js:642:8)
    at strictFail (C:\Users\zhou\Desktop\CooCoo\note\node_modules\xml2js\node_mo
dules\sax\lib\sax.js:662:22)
    at Object.write (C:\Users\zhou\Desktop\CooCoo\note\node_modules\xml2js\node_
modules\sax\lib\sax.js:961:13)
    at Parser.exports.Parser.Parser.parseString (C:\Users\zhou\Desktop\CooCoo\no
te\node_modules\xml2js\lib\xml2js.js:478:31)
    at Parser.parseString (C:\Users\zhou\Desktop\CooCoo\note\node_modules\xml2js
\lib\xml2js.js:6:59)
    at Request._callback (C:\Users\zhou\Desktop\CooCoo\note\spider\content.js:14
:12)
    at Request.self.callback (C:\Users\zhou\Desktop\CooCoo\note\node_modules\req
uest\request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\zhou\Desktop\CooCoo\note\node_modules\reque
st\request.js:1050:14)
    at Request.emit (events.js:129:20)

**Comment by Leonidas-from-XIV** [comment]
Can you post a short example code including the XML you're trying to parse?

**Comment by tflanagan** [comment]
I imagine it looks like this:

```xml
<root>
  <node>text<node</node>
</root>
<invalid>text</invalid>
```

With ```root``` being defined in the parser as the root element.

**Comment by CooCooooo** [comment]
Oh, lt's a long time ago, I almost forget the cause, but I'm sure this error do nothing with the node-xml2js
