### ISSUE TITLE
No Compatible version found: xmlbuilder@'^4.1.0'

### ISSUE THREAD

**Issue by generalconsensus** [Leonidas-from-XIV/node-xml2js#276]
I recently ran into a problem with xml2js which I think might be related to older versions of node. 

I am patching a grunt repo for https://github.com/linusnorton/grunt-parallel-behat and was using 
node 0.8.28
npm 1.2.30
nvm 0.30.2

When I received this message:

```
npm ERR! Error: No compatible version found: xmlbuilder@'^4.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.8","0.3.9","0.3.10","0.3.11","0.4.0","0.4.1","0.4.2","0.4.3","1.0.0","1.0.1","1.0.2","1.1.0","1.1.1","1.1.2","2.0.0","2.0.1","2.1.0","2.2.1","2.3.0","2.4.0","2.4.1","2.4.2","2.4.3","2.4.4","2.4.5","2.4.6","2.5.0","2.5.1","2.5.2","2.6.0","2.6.1","2.6.2","2.6.3","2.6.4","2.6.5","3.0.0","3.1.0","4.0.0","4.1.0","4.2.0","4.2.1"]
npm ERR!     at installTargetsError (/Users/dannymacom/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /Users/dannymacom/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/Users/dannymacom/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by tflanagan** [comment]
Try using `xml2js` version `0.4.15`, that uses `xmlbuilder` version `2.4.6`

**Comment by generalconsensus** [comment]
@tflanagan that seems to be solving my issue, thanks!
