### ISSUE TITLE
Cannot install on Node v6

### ISSUE THREAD

**Issue by Znarkus** [Leonidas-from-XIV/node-xml2js#338]
Hi! Getting these errors with xml2js@0.4.17. Is Node v6 not supported?

```
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:592:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:598:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:603:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:609:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1933:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/.node-gyp/6.8.1/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked
      deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
../src/libxmljs.cc:60:17: warning: 'IsDead' is deprecated [-Wdeprecated-declarations]
    if (v8::V8::IsDead())
                ^
/.node-gyp/6.8.1/include/node/v8.h:8666:10: note: 'IsDead' has been explicitly marked
      deprecated here
bool V8::IsDead() {
         ^
4 warnings and 4 errors generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.nvm/versions/node/v6.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/.nvm/versions/node/v6.8.1/bin/node" "/.nvm/versions/node/v6.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /www/pro5generator/node_modules/libxmljs
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Darwin 15.6.0
npm ERR! argv "/.nvm/versions/node/v6.8.1/bin/node" "/.nvm/versions/node/v6.8.1/bin/npm" "rebuild"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /www/pro5generator/npm-debug.log
```

**Comment by Leonidas-from-XIV** [comment]
I think you're reporting to the wrong project, xml2js does not have any parts in C so your error can't happen. Maybe you're trying to install xml2js-expat or something?

**Comment by Znarkus** [comment]
You are right, sorry! Was thrown off be the name similarity.
