### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by HowardEdidin** [Leonidas-from-XIV/node-xml2js#381]
I have a  Azure node.js function that references the blue-button library.
https://github.com/amida-tech/blue-button

I am getting the following error .

```
2017-04-28T18:26:23.000 Function started (Id=70984dbe-c95c-4061-9764-fc13ced15138)2017-04-28T18:26:23.109 JavaScript HTTP trigger function processed a request.2017-04-28T18:26:23.957 Function completed (Failure, Id=70984dbe-c95c-4061-9764-fc13ced15138, Duration=950ms)2017-04-28T18:26:24.004 Exception while executing function: Functions.GetSectionFromCCD. mscorlib: Error: A dynamic link library (DLL) initialization routine failed.\\?\D:\home\site\wwwroot\GetSectionFromCCD\node_modules\libxmljs\build\Release\xmljs.node    
at Error (native)    
at Object.Module._extensions..node (module.js:583:18)    
at Module.load (module.js:473:32)    
at tryModuleLoad (module.js:432:12)    
at Function.Module._load (module.js:424:3)    
at Module.require (module.js:483:17)    
at require (internal/module.js:20:19)    at bindings (D:\home\site\wwwroot\GetSectionFromCCD\node_modules\bindings\bindings.js:76:44)    
at Object.<anonymous> (D:\home\site\wwwroot\GetSectionFromCCD\node_modules\libxmljs\lib\bindings.js:1:99)    
at Module._compile (module.js:556:32).
```

My function is:

```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    var bb = require('blue-button');

     if (req.query.id && req.body)
     {
         var doc = req.body;
         var section = req.query.id;

         var result = bb.parseString(doc, { component: section });

         if (result) {

             context.res.writeHead(200, { 'Content-Type': 'application/json', 'x-ms-description': 'Success' });
             context.res.end(JSON.stringify(result, null, 4));

           } else {

                context.res.writeHead(400, 'Invalid Document Type',
                    { 'Content-Type': "application/json", 'x-ms-description': 'Bad Request' });
                context.res.end('Invalid Document Type');
           }   


     } else {
          context.res.writeHead(405, 'Missing XmlDoc or Section Id',
                { 'Content-Type': "application/json", 'x-ms-description': "Method No Allowed" });
            context.res.end();
   
     };

    context.done();
};
```

**Comment by Leonidas-from-XIV** [comment]
This is `libxmljs`, not `xml2js`, you need to report this to another bugtracker.

**Comment by HowardEdidin** [comment]
Sorry
