### ISSUE TITLE
Malformed xml not detected in callback

### ISSUE THREAD

**Issue by GiordanoArman** [Leonidas-from-XIV/node-xml2js#408]
Hi, I am using parseString to parse a string that looks like this:

`<Transaction />
  <Transaction /> 
</confirmation>`

using code that looks like this

`parseString(xml, function (err, res) {});`

A malformed xml error is thrown, but only after the callback is triggered and the err variable is null and the res variable is an object containing Transaction tag data.

Wouldn't it be better to get the error in the callback?

**Comment by Leonidas-from-XIV** [comment]
> Wouldn't it be better to get the error in the callback?

I agree, this definitely should happen! Error handling is currently extremely bad.

**Comment by jcsahnwaldt** [comment]
See https://github.com/Leonidas-from-XIV/node-xml2js/issues/67

**Comment by jcsahnwaldt** [comment]
Test code to reproduce issue:
```js
const xml2js = require('xml2js');
let xml = `<Transaction /> <Transaction /> </confirmation>`;
try {
  xml2js.parseString(xml, (err, res) => {
    console.log('callback err:');
    console.log(err);
    console.log('callback res:');
    console.log(res);
  });
}
catch (err) {
  console.log('caught err:');
  console.log(err);
}
```
Output (paths in stacktrace sanitized):
```
callback err:
null
callback res:
{ Transaction: '' }
caught err:
Error: Unmatched closing tag: confirmation
Line: 0
Column: 47
Char: >
    at error (./node_modules/sax/lib/sax.js:651:10)
    at strictFail (./node_modules/sax/lib/sax.js:677:7)
    at closeTag (./node_modules/sax/lib/sax.js:879:7)
    at SAXParser.write (./node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (./node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (./node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (./node_modules/xml2js/lib/parser.js:354:19)
    at Object.<anonymous> (./test.js:4:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
