### ISSUE TITLE
Unable to show output of xml file

### ISSUE THREAD

**Issue by softwar3d3v** [Leonidas-from-XIV/node-xml2js#424]
I'm trying to load an XML file using the xml2js parser and the result turns out undefined. 
```node
 fs.readFile(filePath, function(err, data) {
      parser.parseString(data, function (err, result) {
        console.dir(result);
        console.log(err);
        console.log('Done');
      });
  });
```
And I get this error:
```text
TypeError: Cannot read property 'toString' of undefined
at Parser.exports.Parser.Parser.parseString (C:\Users\Taylor\cognitivedata\express-app\node_modules\xml2js\lib\parser.js:311:19)
at Parser.parseString (C:\Users\Taylor\cognitivedata\express-app\node_modules\xml2js\lib\parser.js:5:59)
at ReadFileContext.callback (C:\Users\Taylor\cognitivedata\express-app\routes.js:39:14)
at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by Leonidas-from-XIV** [comment]
Are you sure the file loaded? You're never checking for errors.

**Comment by jcsahnwaldt** [comment]
@softwar3d3v Can this issue be closed?
