### ISSUE TITLE
Parse String Error

### ISSUE THREAD

**Issue by khushroo-mistry** [Leonidas-from-XIV/node-xml2js#438]
Input XML String: "<property><value>55</value></property>"

Usage:

```
let parseString = xml2js.parseString;
function extractCredentials( soapRequest ) {
    let options = {
        explicitArray: false,
        attrkey: "attributes",
        charkey: "value",
        normalizeTags: true,
        ignoreAttrs: true
    };
    const soapEnvelopToCredentialsMap = {
        "passwordtext": "password",
        "usernametoken": "username",
        "secret": "secret",
        "callingsystem": "callingSystem"
    };
    let credentials = {};

    return new Promise( function ( resolve, reject ) {
        parseString( soapRequest, options, function ( err, result ) {

            if ( err ) {
                console.log(err.toString());
                return reject( new BadRequestError( BAD_REQUEST_ERR_MSG, err ) );
            }

            console.log(result);

            let flattenedResult = jsonFlatten( result );
            Object.keys( flattenedResult ).forEach( function ( soapEnvelopKey ) {
                Object.keys( soapEnvelopToCredentialsMap ).forEach( function ( mapKey ) {
                    if ( soapEnvelopKey.endsWith( mapKey ) ) {
                        let credentialsKey = soapEnvelopToCredentialsMap[ mapKey ];
                        credentials[ credentialsKey ] = flattenedResult[ soapEnvelopKey ];
                    }

                } )
            } );

            return resolve( credentials );
        } );
    } );
}
```

```
Error: TypeError: obj[charkey].match is not a function
       at Object.onclosetag (/Library/WebServer/Documents/flexssoservice/node_modules/xml2js/lib/parser.js:184:28)
       at emit (/Library/WebServer/Documents/flexssoservice/node_modules/sax/lib/sax.js:624:35)
       at emitNode (/Library/WebServer/Documents/flexssoservice/node_modules/sax/lib/sax.js:629:5)
       at closeTag (/Library/WebServer/Documents/flexssoservice/node_modules/sax/lib/sax.js:889:7)
       at Object.write (/Library/WebServer/Documents/flexssoservice/node_modules/sax/lib/sax.js:1436:13)
       at Parser.exports.Parser.Parser.parseString (/Library/WebServer/Documents/flexssoservice/node_modules/xml2js/lib/parser.js:322:31)
       at Parser.parseString (/Library/WebServer/Documents/flexssoservice/node_modules/xml2js/lib/parser.js:5:59)
       at exports.parseString (/Library/WebServer/Documents/flexssoservice/node_modules/xml2js/lib/parser.js:354:19)
       at /Library/WebServer/Documents/flexssoservice/helpers/soapObjectsHandler.js:9:1180
       at Object.extractCredentials (/Library/WebServer/Documents/flexssoservice/helpers/soapObjectsHandler.js:9:1066)
       at Context.<anonymous> (/Library/WebServer/Documents/flexssoservice/test/helpers/helpers.soapObjectsHandler.extractCredentials.test.js:38:35)
       at callFn (/Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runnable.js:326:21)
       at Test.Runnable.run (/Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runnable.js:319:7)
       at Runner.runTest (/Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runner.js:422:10)
       at /Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runner.js:528:12
       at next (/Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runner.js:342:14)
       at /Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runner.js:352:7
       at next (/Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runner.js:284:14)
       at Immediate.<anonymous> (/Library/WebServer/Documents/flexssoservice/node_modules/mocha/lib/runner.js:320:5)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5)
```

The input is a valid XML why is this failing? This is an issue in production can this be looked at immediately?

**Comment by RikkiGibson** [comment]
Seems like xml2js is not gracefully handling the ambiguity between the charkey "value" and the element named "value". You should be able to work around this by picking a charkey that is unlikely to be used as an element name in your data (even "_value" might be adequate).

**Comment by jcsahnwaldt** [comment]
Basically the same problem as in #385
