### ISSUE TITLE
Unable to parse a xml buffer with encoded url to xml using parseString

### ISSUE THREAD

**Issue by chetan-plrch** [Leonidas-from-XIV/node-xml2js#498]

**Comment by chetan-plrch** [comment]
Got this error,

Failed Error parsing, in parseString Error: Invalid character in entity name
Line: 64
Column: 285
Char: %
    at error (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/node_modules/sax/lib/sax.js:693:7)
    at SAXParser.write (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/node_modules/sax/lib/sax.js:1504:13)
    at Parser.exports.Parser.Parser.parseString (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/node_modules/xml2js/lib/parser.js:354:19)
    at Promise (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/sitemapHandler.js:233:9)
    at new Promise (<anonymous>)
    at convertXmlToJson (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/sitemapHandler.js:232:12)
    at editEntriesFromSitemap (/home/chetan/company/lambdas/cmsSitemapCreator/lambda/sitemapHandler.js:20:32)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by Leonidas-from-XIV** [comment]
Looks like you have an entity with invalid characters in your XML. How does the XML look like at the location the error message states?

**Comment by chetan-plrch** [comment]
i am having xml buffer to parse

**Comment by chetan-plrch** [comment]
<?xml-stylesheet type="text/xsl" href="//domainname.com/main-sitemap.xsl"?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>https://domainname.com/ideal-y5vrwp5ia7</loc>
        <lastmod>2018-12-26T09:23:01.743Z</lastmod>
        <image:image>
            <image:loc>https://images.domainname.com/cs/1/b3/Are%20the%20ideal%20features%20&%20functionalities%20of%20Lab%20Information%20Management%20Webiste%20and%20its%20Mobile%20app1545628606621.jpg</image:loc>
        </image:image>
    </url>
</urlset>

**Comment by chetan-plrch** [comment]
<?xml-stylesheet type="text/xsl" href="//domainname.com/main-sitemap.xsl"?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>https://domainname.com/ideal-y5vrwp5ia7</loc>
        <lastmod>2018-12-26T09:23:01.743Z</lastmod>
        <image:image>
            <image:loc>https://images.domainname.com/cs/1/b3/Are%20the%20ideal%20features%20&%20functionalities%20of%20Lab%20Information%20Management%20Webiste%20and%20its%20Mobile%20app1545628606621.jpg</image:loc>
        </image:image>
    </url>
</urlset>

**Comment by chetan-plrch** [comment]
```<?xml-stylesheet type="text/xsl" href="//domainname.com/main-sitemap.xsl"?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>https://domainname.com/ideal-y5vrwp5ia7</loc>
        <lastmod>2018-12-26T09:23:01.743Z</lastmod>
        <image:image>
            <image:loc>https://images.domainname.com/cs/1/b3/Are%20the%20ideal%20features%20&%20functionalities%20of%20Lab%20Information%20Management%20Webiste%20and%20its%20Mobile%20app1545628606621.jpg</image:loc>
        </image:image>
    </url>
</urlset>```

**Comment by chetan-plrch** [comment]
Had to use strict: false and normalizeTags: true, and everything worked fine. besides the xmlns arrtributes are appearing in Uppercase didn't expect that.
