### ISSUE TITLE
parseString callback never called

### ISSUE THREAD

**Issue by frederic-kieu** [Leonidas-from-XIV/node-xml2js#51]
I am using xml2js to parse XML-data from an external source I do not control.

I recently encountered a piece of invalid XML that caused parseString to not call the callback, ever. Not with a result, not even with an error.

Here's a sample node app and 2 XML-files that cause the described behavior:

test.js:

``` javascript
var fs = require( "fs" ), xml2js = require( "xml2js" );

var parser = new xml2js.Parser();
fs.readFile( __dirname + "/foo.xml", function( err, data ) {
    if( err ) {
        console.log( "file io error: " + err );
        return;
    }
    parser.parseString( data, function( err, res ) {
        // never reached
        if( err ) {
            console.log( "parse error: " + err );
            return;
        }
        console.dir( res );
        console.log( "done" );
    } );
} );
```

foo.xml:

``` xml
<?xml version="1.0"?>
```

foo2.xml

``` xml
<?xml version="1.0"?>
This is a string.
This is another string.
```

**Comment by voronianski** [comment]
@Leonidas-from-XIV I'm having that issue right now with version `0.4.6` that is latest:

```bash
[Error: Unclosed root tag
Line: 0
Column: 15
Char: ]

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unclosed root tag
Line: 0
Column: 15
Char:
    at error (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
    at end (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/node_modules/sax/lib/sax.js:649:27)
    at Object.write (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/node_modules/sax/lib/sax.js:916:30)
    at Object.SAXParser.close (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/node_modules/sax/lib/sax.js:152:38)
    at Parser.exports.Parser.Parser.processAsync (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/lib/xml2js.js:249:31)
    at Object._onImmediate (/Users/dmitri/trinity-mirror/football-modular/football-betting-api/node_modules/xml2js/lib/xml2js.js:6:59)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

That's very annoying 'cause it crashes the app and I have no chance to intercept it in callback of `parseString`.

**Comment by Leonidas-from-XIV** [comment]
Can you post a simple XML to reproduce?

**Comment by voronianski** [comment]
@Leonidas-from-XIV just try `'<xml>POST VALUE'`.

**Comment by voronianski** [comment]
@Leonidas-from-XIV I know that response is extremely invalid but I'm working with resource that can send crazy responses..

**Comment by saurabhtaneja** [comment]
You can take the xml in blocks and if find any new line then add into the block if index goes to - then console you will find full xml then use it like 
var callbackres = callbackresxml.toString('utf8');	
            callbackblock += callbackres;
            if(callbackres.indexOf("\n")> -1){console.log(callbackblock );}

**Comment by raeesaa** [comment]
Even I am facing 'Unclosed Root Tag' error for valid XML. The version of library I am using is 0.4.4. Was anyone able to find workaround for this?

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unclosed root tag
Line: 1098
Column: 274
Char: 
    at error (/home/user/user/Test/node_modules/xml2js/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/home/user/user/Test/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
    at end (/home/user/user/Test/node_modules/xml2js/node_modules/sax/lib/sax.js:649:27)
    at Object.write (/home/user/user/Test/node_modules/xml2js/node_modules/sax/lib/sax.js:916:30)
    at Object.SAXParser.close (/home/user/user/Test/node_modules/xml2js/node_modules/sax/lib/sax.js:152:38)
    at Parser.exports.Parser.Parser.parseString (/home/user/user/Test/node_modules/xml2js/lib/xml2js.js:403:67)
    at Parser.parseString (/home/user/user/Test/node_modules/xml2js/lib/xml2js.js:6:61)
    at Socket.<anonymous> (/home/user/user/Test/ftpfileSaveWorker.js:43:20)
    at Socket.emit [as _emit] (events.js:95:17)
    at Socket.source.emit (/home/user/user/Test/node_modules/ftp/lib/connection.js:564:20)

```

**Comment by Leonidas-from-XIV** [comment]
Can you post your XML? Does it work when using the default settings?

**Comment by Shadowstep33** [comment]
This is happening to me as well using the following xml:

```<root>Hello xml2js!</root>```

I am using FS to parse a file from a local path; when I console.log the data from fs readFile then I get a buffer. Can parseString handle buffers? If not, I'd posit a guess that's the problem.

```
var asset_hitboxes;
var parser = new xml2js.Parser();
fs.readFile(__dirname + '/assets_test.xml', function(err, data) {
    parser.parseString(data, function (err, result) {
		asset_hitboxes = result;
        console.dir(err, result);
        console.log('Done');
    });
});
```

**Comment by Shadowstep33** [comment]
Yah actually well, I was pointing to the wrong file xD buuuuuuuuuuuuut it seems that there was still a problem parsing the buffer. this code seems to work assuming my above quoted xml:

```
var asset_hitboxes;
var parser = new xml2js.Parser();
fs.readFile(__dirname + '/assets_test.xml', "utf-8", function(err, data) {
	console.log(data)
    parser.parseString(data, function (err, result) {
		asset_hitboxes = result;
        console.dir(err, result);
        console.log('Done');
    });
});
```

**Comment by Power8000** [comment]
fs don't work , how to customise
