### ISSUE TITLE
Bug: TypeError

### ISSUE THREAD

**Issue by yevgenypats** [Leonidas-from-XIV/node-xml2js#544]
Hey there,

The following code produce `TypeError: obj[charkey].match is not a function`

```javascript
xml2js = require('xml2js');
var parser = new xml2js.Parser();
parser.parseString(Buffer.from('3c4f3eff00002f3e3c5f2f3e3c2f4f3eff3e4f3ead3ce42f3e3ce4c9ff002fe4ad5f0109900aad3c4f3ead', 'hex')).toString()

TypeError: obj[charkey].match is not a function
    at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:187:28)
    at emit (/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:325:31)
    at Parser.parseString (/node_modules/xml2js/lib/parser.js:5:59)
```

It was found by [jsfuzz](https://github.com/fuzzitdev/jsfuzz)

Cheers,
Yevgeny

**Comment by Omega-Ariston** [comment]
You may wanna double check the structure of your input XML. I tried several encoding format but none of them parsed to a correct XML.
![8](https://user-images.githubusercontent.com/32405587/73623496-14f76980-4678-11ea-89dc-77e5cea20186.png)

**Comment by noBlubb** [comment]
Input generated by the fuzzer (jsfuzz) is likely to not be valid xml. The library should be able to detect this properly instead of throwing a generic TypeError when accessing an invalid property / function.
