### ISSUE TITLE
Error: Non-whitespace before first tag. Line: 0 Column: 1 Char: 

### ISSUE THREAD

**Issue by balibebas** [Leonidas-from-XIV/node-xml2js#595]
This should work out of the box, since xml2js has now code to remove the byte order mark before parsing.

_Originally posted by @Leonidas-from-XIV in https://github.com/Leonidas-from-XIV/node-xml2js/issues/345#issuecomment-264904146_

But it doesen't. To reproduce the error:

```sh
curl -O https://habd.as/post/index.xml
npm i -g xml2js@0.4.23
```

Drop in the script provided in #345:

```js
const fs = require('fs');
const util = require('util')
const parseString = require('xml2js').parseString;
const fileToParse = ('./index.xml')
const outputFilename=('output.json')

fs.readFile(fileToParse, function (err, data) {
    parseString(data, function (err, result) {
        console.dir(result);
        if (err) {
            console.log(err)
        }
       // do something with the JS object called result, or see below to save as JSON
        fs.writeFile('output.json', JSON.stringify(result), (writeErr) => {
            if (writeErr) throw writeErr;
            console.log('The file has been saved to ' + outputFilename);
        });
    });
});
```

And you'll get the output:

```

undefined
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 
    at error (/Users/jos/Developer/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/jos/Developer/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/jos/Developer/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/jos/Developer/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/Users/jos/Developer/node_modules/xml2js/lib/parser.js:323
:31)
    at Parser.parseString (/Users/jos/Developer/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/Users/jos/Developer/node_modules/xml2js/lib/parser.js:369:19)
    at /Users/jos/Developer/balibebas-gh-repo/parse.js:8:5
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
The file has been saved to output.json
```

This is causing issues in the following consumer:
https://github.com/rbren/rss-parser

And a consumer of that library:
https://github.com/gautamkrishnar/blog-post-workflow

Which is being shared as a method to add latest posts to a GH profile:
https://www.yellowduck.be/posts/add-your-latest-blog-posts-your-github-profile/

What's the expected functionality? As it stands BOM chars seem to be bombing this lib.

**Comment by balibebas** [comment]
After pulling open the file with a hex editor I wasn't able to identify a BOM character at the beginning of the file. Turns out the XML being served by my object storage provider (static site) was malformed—potentially due to an incomplete upload.

Here's what Firefox showed:

<img width="667" alt="Screen Shot 2020-12-17 at 11 25 08 AM" src="https://user-images.githubusercontent.com/65664227/102440128-a090a380-405a-11eb-84c0-f7a1e94b17ee.png">

So it seems this is a non-issue. I resolved it no my end with a manual file deletion and simply re-uploaded the XML and it's no longer issuing. ¯\_(ツ)_/¯

**Comment by Q118** [comment]
I don't think this is the most elegant way to go about it. But I was able to get rid of theerror by parsing the string of xml.
```js
let data = JSON.parse(JSON.stringify(myRequest.responseText))
 data = parseString(data, (err, result) => {
      console.dir(result);
      if (err) {
        console.log(err);
      }
    })
```
