### ISSUE TITLE
Malformed XML sneaks by callback version of parseString

### ISSUE THREAD

**Issue by mandrewpowers** [Leonidas-from-XIV/node-xml2js#617]
When parsing the same malformed XML, `<root></root></root>`, through the synchronous and asynchronous versions of `parseString` one returns `{ "root": "" }` and the other correctly throws an error.
Unless I somehow misunderstood the API this seems quite incorrect. I expected the callback to receive a populated `err` argument. The same of course happens to the promisified version.

*Node:* `v12.16.1`
*xml2js:* `0.4.23`

*Example:*
```
> xml2js.parseString(`<root></root></root>`, {}, (err, result) => console.log(`Results: err=${err}, result=${JSON.stringify(result)}`))
Results: err=null, result={"root":""}
undefined
> xml2js.parseString(`<root></root></root>`, {})
Uncaught Error: Unmatched closing tag: root
Line: 0
Column: 20
Char: >
    at error (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/sax/lib/sax.js:879:7)
    at SAXParser.write (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/Users/andrewpowers/simplisafe/palpatine/files/src/node_modules/xml2js/lib/parser.js:369:19)
```

**Comment by mandrewpowers** [comment]
Updated once I realized I seem to be using the API incorrectly when not passing a callback. This may be a sax problem, but I'm honestly not sure.

**Comment by mandrewpowers** [comment]
*Last additional comment:*

Noticed if the extra token is an orphaned opening tag such as `<root></root><root>`, it is also not detected since the stack seems to clean up even if the stream still has left over token(s).

**Comment by Leonidas-from-XIV** [comment]
While I agree that this is surprising, it is not all that unexpected since xml2js aims to parse one item from the string and by the time the `</root>` is encountered the tree is finished, so whatever comes afterwards can be ignored (it probably *should not* be ignored, because that means it accepts invalid XML but I would assume that many JSON parsers also accept `{}}` as input only to discard everything after a complete object has been parsed from the input stream.

**Comment by andrew-stupchuk** [comment]
same issue: first time parseString return an error, for second try i received object with incorrect data . any workarounds?
