### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by damianof** [Leonidas-from-XIV/node-xml2js#651]
Getting this with version 0.4.23:

Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:222:46
    at node_modules/sax/lib/sax.js (sax.js:1565:1)
    at __require (chunk-UNANNA3Z.js?v=1c06db08:38:50)
    at Object.<anonymous> (parser.js:9:9)
    at node_modules/xml2js/lib/parser.js (parser.js:381:4)
    at __require (chunk-UNANNA3Z.js?v=1c06db08:38:50)
    at Object.<anonymous> (xml2js.js:12:12)
    at node_modules/xml2js/lib/xml2js.js (xml2js.js:39:4)
    at __require (chunk-UNANNA3Z.js?v=1c06db08:38:50)
    at dep:xml2js:1:16
    

SAXStream.prototype = Object.create(Stream.prototype, { // Stream seems to be undefined
    constructor: {
      value: SAXStream
    }
  })

**Comment by mathieuguyot** [comment]
Hi I faced the same issue, if you are using vite, please take a look at https://github.com/vitejs/vite/issues/7555
what worked for me was to add 
`  resolve: {
    alias: {
      stream: "stream-browserify"
    }
  }`
inside the defineConfig of your vite.config.ts

**Comment by BugKiller-tech** [comment]
Hi, Should I install the npm package `stream-browserify`?

**Comment by devmanzur** [comment]
`npm i stream-browserify`

**Comment by anisjonischkeit** [comment]
Setting a resolution to force a later version of sax resolved this for me
```
  "resolutions": {
    "sax": "^1.4.1",
  }
```
