### ISSUE TITLE
any clue about this issue?

### ISSUE THREAD

**Issue by shailendra9** [Leonidas-from-XIV/node-xml2js#98]
shailendrapathak@dd-D32:~/Desktop$ node parsedocx.js

/home/shailendrapathak/node_modules/xml2js/lib/xml2js.js:269
      if (str.toString().trim() === '') {
              ^
TypeError: Cannot call method 'toString' of undefined
    at Parser.exports.Parser.Parser.parseString (/home/shailendrapathak/node_modules/xml2js/lib/xml2js.js:269:15)
    at Parser.parseString (/home/shailendrapathak/node_modules/xml2js/lib/xml2js.js:6:61)
    at processMainDocument (/home/shailendrapathak/Desktop/parsedocx.js:65:9)
    at Object.<anonymous> (/home/shailendrapathak/Desktop/parsedocx.js:57:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by Omnomios** [comment]
I encountered this problem as well. I was passing an undefined.
It would be prudent to not 'crash' node but check for it in the library and pass something in the err of the callback.

It was confusing that your call was completing but not doing what was expected of it.
